### ISSUE TITLE
Error ao interagir com algum item na versão spigot-1.18.2-R0.1-SNAPSHOT

### ISSUE THREAD

**Issue by TakuiasH** [NextPlugins/NextEconomy#32]
![image](https://user-images.githubusercontent.com/59321488/163199708-7e5da4ba-8115-44b4-8c54-26defb63ee3a.png)

**Comment by eikefab** [comment]
A dependência de NBT do plugin não foi atualizada a 1.18.2. Será corrigido em breve.

**Comment by eikefab** [comment]
Problema solucionado na versão 2.1.1 do plugin.
