### ISSUE TITLE
Erro na inicialização

### ISSUE THREAD

**Issue by tecMT** [NextPlugins/NextEconomy#34]

**Comment by tecMT** [comment]
https://prnt.sc/UZQR_WVMacYe

**Comment by gabrielbs21** [comment]
Olá, esse é um erro de configuração, no caso, a branch em que estava esse novo sistema de NPCs (com animações) foi mesclada com a branch principal e esquecemos de avisar desse novo sistema. A solução atualmente é fazer um backup do seus arquivos de configurações atuais e apagá-los para ser gerado os novos, em breve faremos um "tutorial" de como atualizar de maneira segura para esta nova release.
