### ISSUE TITLE
[1.16.5] Adicionar HEX Color 

### ISSUE THREAD

**Issue by viminio** [NextPlugins/NextEconomy#38]
![Screenshot_1](https://user-images.githubusercontent.com/62722905/189203893-4e06bac8-7a68-4630-9072-3a5002209057.png)
Olha como fica sem o suporte pra HEX Color na 1.16 os npc fica tudo bugado

**Comment by eikefab** [comment]
Função adicionada na versão [2.2.0](https://github.com/NextPlugins/NextEconomy/releases/tag/2.2.0) do plugin.
