### ISSUE TITLE
[Bug] Banco do SuperiorSkyBlock

### ISSUE THREAD

**Issue by N1kyZ** [NextPlugins/NextEconomy#39]
Parece que o NextEconomy não adiciona o dinheiro no banco do SuperiorSkyblock, mas ele remove da conta do jogador.

![image](https://user-images.githubusercontent.com/58773688/201803975-fb0724ab-601b-4af2-966e-31b0873c7bb9.png)

![image](https://user-images.githubusercontent.com/58773688/201804033-2c4f6962-cd19-4102-9448-7ce3a127b3d0.png)

![image](https://user-images.githubusercontent.com/58773688/201804131-cc5bc7a7-bbed-4e24-8806-770bd00e7902.png)

Eu acredito que pode ter problema com o NextEconomy já que é o unico plugin de economia que testei que da esse problema.

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

NextEconomy version 2.1.4
SuperiorSkyblock2 version 2022.9-b900

**Comment by Yuhtin** [comment]
@eikefab alguma ideia do que ta acontecendo aqui?

**Comment by eikefab** [comment]
Sim.

Pelo que vi [aqui](https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/472371ee9131d12ec29d08946beea6b711259b23/Hook_Vault/src/main/java/com/bgsoftware/superiorskyblock/external/economy/EconomyProvider_Vault.java#L33), o SuperiorSkyblock usa o sistema de banco do Vault, que não foi implementado no NextEconomy, como pode ver [aqui](https://github.com/NextPlugins/NextEconomy/blob/309e8dfb99584d7a209eadfc881983c9820b2b3b/src/main/java/com/nextplugins/economy/vault/EconomyWrapper.java#L112). E por não checar se há compatibilidade com o sistema de banco antes, o SuperiorSkyblock acaba por usar funções que não foram implementadas no NextEconomy.
