### ISSUE TITLE
Não é possível usar o plugin com a mesma database em dois servidores (MySQL)

### ISSUE THREAD

**Issue by emanuelVINI01** [NextPlugins/NextEconomy#41]
Então, mesmo que você coloque as mesmas configurações do MySQL no plugin em dois servidores, em um o saldo fica diferente do outro.

**Comment by eikefab** [comment]
O plugin não tem suporte oficial para sincronização. Apesar de existir o [NextEconomyBungeeHook](https://github.com/NextPlugins/NextEconomyBungeeHook), ele foi descontinuado.
