### ISSUE TITLE
Alguns icones do /money estão indo para o inventário do jogador quando clica

### ISSUE THREAD

**Issue by lucpes** [NextPlugins/NextEconomy#42]
quando digito /money , o icone do ativar/desativar recebimento está indo para o meu inventário, além das cabeças que aparecem no money top. Queria saber como resolver

**Comment by eikefab** [comment]
Não consegui replicar. Talvez seja um problema de conexão e o item seria apenas visual. Ao tentar usá-lo ou colocá-lo no chão, seria removido automaticamente pelo servidor.
