### ISSUE TITLE
Error NextEconomy severe error

### ISSUE THREAD

**Issue by ShizenXD** [NextPlugins/NextEconomy#48]
![image](https://github.com/NextPlugins/NextEconomy/assets/107296268/a3129918-adfe-4a94-b65b-0a8f5f38ca93)
![image](https://github.com/NextPlugins/NextEconomy/assets/107296268/b89f6630-c619-47ca-b0a7-d8612b42b9df)

**Comment by Tarekizor** [comment]
Já resolveu?

**Comment by ShizenXD** [comment]
no

**Comment by ShizenXD** [comment]
quando eu clico com o botão direito do mouse

**Comment by Tarekizor** [comment]
Acho que é a biblioteca que está desatualizada, tá dando o mesmo erro pra mim quando o jogador põe blocos ou tem interações com algum bloco que tenha funcionalidade (cama, bigorna, baú)

**Comment by Tarekizor** [comment]
@Yuhtin  @henrysaantos @nickuc

Corrige o erro aí seus lindos, por favor <3 (esse é o melhor plugin de economia da atualidade e queria muito usar na 1.20.4)

**Comment by Tarekizor** [comment]
@ShizenXD achei um plugin similar, se chama yEconomy. Ele é pago, custa 15 reais. Embora o NextEconomy tenha mais recursos, acho que não vão mais atualizar, estão a muito tempo sem responder :/

**Comment by ShizenXD** [comment]
@Tarekizor achei um chamado lightEconomy e tem até mais recursos

**Comment by eikefab** [comment]
Erro corrigido na #49.
